### PR TITLE
Fix for #12

### PR DESCRIPTION
**Pull request by andrrr**
https://github.com/symphonists/cacheabledatasource/issues/12

### CODE REVIEW

**Comment by nitriques** [comment]
Thanks! But, if you could, please re-do the PR and

1. Push it against `integration` branch.
2. Do not change whitespace settings since it makes diff really hard.

Thanks!

**Comment by brendo** [comment]
Don't forget Github's whitespace hack, [`?w=0`](https://github.com/symphonists/cacheabledatasource/pull/19/files?w=0)

**Comment by michael-e** [comment]
> Don't forget Github's whitespace hack, `?w=0`

I never knew, thanks for sharing!

**Comment by andrrr** [comment]
Ок

**Comment by nitriques** [comment]
> Don't forget Github's whitespace hack

I did, and it still hard to read, sadly...

**Comment by nitriques** [comment]
Oh I got confused with the single line if statements.

@andrrr Would you also mind putting the if body in {} and on their own line please ?

**Comment by nitriques** [comment]
This has been fixed in 1c32103...99c4ed0

**Pull request closed without merging**
