### PR TITLE
Bugfix Filename cannot be empty

### PR DESCRIPTION
**Pull request by wdebusschere**

### CODE REVIEW

**Comment by nitriques** [comment]
Can you elaborate more on your fix ?

**Comment by nitriques** [comment]
When are you getting an error ? while saving ?

**Comment by wdebusschere** [comment]
I had made a mistake with the code, should have been after this  if (!file_exists($filename))  if not there is an error.

**Comment by nitriques** [comment]
It's my fault this bug was introduce: your original PR was ok! Sorry!

**Pull request merged**
